name: docs CI 

on:
  workflow_dispatch:
    inputs:
      version:
        required: false
        description: 'version name'
        default: "master"
        type: string

  # pull_request:
  #   branches:
  #     - "master"

jobs:
  install_dependencies_and_deploy:
    name: install dependencies and deploy latest changes to prod
    runs-on: ubuntu-latest
    steps:
        - name: checkout latest
          uses: actions/checkout@v3
          with:
            ref: ${{ inputs.version }}
            fetch-depth: 0

        - name: setup python
          uses: actions/setup-python@v4
          with:
            python-version: '3.9'
            cache: 'pip' # caching pip dependencies

        - name: install dependencies
          run: |
           pip3 install -r requirements.txt
        
        - name: Configure Git User
          run: |
            git config user.name "circleci-runai"
            git config user.email "circleci-runai@run.ai"
#            git fetch origin gh-pages --depth=1
        
        - name: deploy mkdocs latest
#          run: mkdocs gh-deploy --force
#          echo "deploy new version with mike..."
          if: ${{ inputs.version == 'v2.9' }}
          run: | 
            mike deploy --push ${{ inputs.version }} 2.9
            mike set-default 2.9 --ignore
        - name: deploy mkdocs version
          if: ${{ inputs.version != 'v2.9' }}
          run: mike delete --push v2.9a 
#          |
#            mike deploy --push ${{ inputs.version }} 2.9a
#            mike set-default 2.9 --ignore
             



